import type { Metadata } from "next";
import { Inter, Rubik, IBM_Plex_Sans_Arabic  } from "next/font/google";
import "./globals.css";
import { Locale, i18n } from '@/i18n.config'
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });
const rubik = Rubik({ subsets: ["latin"] });
const ibm = IBM_Plex_Sans_Arabic({ subsets: ["arabic"], weight:"500"});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map(locale => ({ lang: locale }))
}

export default function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale }
}>) {

  // direct page based on lang
  let direction = ''
  if(params.lang === 'ar') {
    direction = 'rtl'
  }
  else {
    direction = 'ltr'
  }

  return (
    <html lang={params.lang} dir={direction} className="scroll-smooth">
      <body className={`${direction !== "rtl" && inter.className || direction === "rtl" && ibm.className}`}>
        <Navbar lang={params.lang} />
        {children}
        <Footer lang={params.lang} />
      </body>
    </html>
  );
}
